#! /usr/bin/perl
use strict;
use JSON;

my $f_config = "/etc/sendmailwrapper/sendmailwrapper.cf";

#$f_config = "./sendmailwrapper.cf" if( -f "./sendmailwrapper.cf");

my $c = parseConfigFile($f_config);
$c->{'errorlog'} = "/tmp/sendmailwrapper.error" if(!defined($c->{'errorlog'}));

# Parse headers to get stuff to log/judge with:
my $emaildata;

$emaildata->{'args_string'} = join(" ", @ARGV);
$emaildata->{'directory'} = $ENV{'PWD'};
$emaildata->{'apache_run_user'} = $ENV{'APACHE_RUN_USER'};
$emaildata->{'apache_run_group'} = $ENV{'APACHE_RUN_GROUP'};

my ($to, $from, $subject, $phpScript, $client, @message);
while(<STDIN>){
	if (/^to:\s*(.+)\s*$/i){ 
		$emaildata->{'to'} = $1;
	}elsif(/^from:\s*(.+)\s*$/i){
		$emaildata->{'from'} = $1;
	}elsif(/^subject:\s*(.+)\s*$/i){
		$emaildata->{'subject'} = $1;
	}elsif(/^x-php-(originating-)?script:\s*(\S+)\s*for\s*(\S+)s*$/i){
		$emaildata->{'script'} = $2;
		$emaildata->{'client'} = $3;
		$emaildata->{'scriptfilename'} = (split("/", $emaildata->{'script'}))[-1];
	}elsif(/^x-php-originating-script:\s*(.+)\s*$/i){
		my $script = $1;
		$emaildata->{'x-php-originating-script'} = $script;
		if($script =~ m/(\d+):(\S+)\((\d+)\)\s+:\s+(.+)$/){
			$emaildata->{'x-php-uid'} = $1;
			$emaildata->{'x-php-scriptfilename'} = $2;
			$emaildata->{'x-php-line'} = $3;
			$emaildata->{'x-php-origin-other'} = $4;
		}elsif($script =~ m/(\d+):(\S+)\((\d+)\)$/){ 
			$emaildata->{'x-php-uid'} = $1;
			$emaildata->{'x-php-scriptfilename'} = $2;
			$emaildata->{'x-php-line'} = $3;
		}elsif($script =~ m/(\d+):(\S+)$/){ 
			$emaildata->{'x-php-uid'} = $1;
			$emaildata->{'x-php-scriptfilename'} = $2;
		}
	}elsif(/^X-Mailer:\s*(.+)\s*$/){
		$emaildata->{'mailer'} = $1;
	}
	push(@message, $_);
}

if(-f $c->{'directoryblacklist'} || -f $c->{'pwdwhitelist'}){
	$emaildata = checkDirectoryBlacklist($c, $emaildata);
	if($emaildata->{'blacklist'} =~ m/directory/){
		_log_json($emaildata, $c->{'blacklistlog_json'});
		blacklist($emaildata, "9");
		exit 2
	}
}

if(-f $c->{'scriptblacklist'} || -f $c->{'scriptwhitelist'}){
	$emaildata = checkScriptBlacklist($c, $emaildata);
	if($emaildata->{'blacklist'} =~ m/script/){
		$emaildata->{'blacklist'} = "script";
		_log_json($emaildata, $c->{'blacklistlog_json'});
		blacklist($emaildata, "12");
		exit 2
	}
}

if(-f $c->{'combinationblacklist'}){
	$emaildata = checkCombinationBlacklist($c, $emaildata);
	if($emaildata->{'blacklist'} =~ m/combination/){
		$emaildata->{'blacklist'} = 'combination';
		_log_json($emaildata, $c->{'blacklistlog_json'});
		blacklist($emaildata, "6");
		exit 2
	}
}


# Write to the log, send the mail and exit:
_log();
_log_json($emaildata, $c->{'sentlog_json'});
sendmail(\@message, \@ARGV);
exit 0;

# # # # #
# # # #
# # #
# #  
#

sub checkCombinationBlacklist{
	my $c = shift;
	my $emaildata = shift;
	my $list;
	if( defined($emaildata->{'x-php-scriptfilename'}) and defined($emaildata->{'directory'}) ){
		$list = getList($c->{'combinationblacklist'});
		foreach my $line (keys(%{$list})){
			my ($directory,$script) = split(m/\s+/, $line);
			if(($directory eq $emaildata->{'directory'}) and ($script eq $emaildata->{'x-php-scriptfilename'})){
				$emaildata->{'blacklist'} = "combination";
				$emaildata->{'blacklist_line'} = $list->{$line};
				$emaildata->{'blacklist_match'} = $line;
				return $emaildata;
			}
		}
	}
	return $maildata;
}


sub checkScriptBlacklist{
	my $c = shift;
	my $emaildata = shift;
	my $list;
	if(defined($c->{'scriptblacklist'}) && defined($emaildata->{'x-php-originating-script'})){
		$list = getList($c->{'scriptblacklist'});
		foreach(keys(%{$list})){
			if(my $lineNumber = $emaildata->{'x-php-originating-script'} =~ m/$_/){
				$emaildata->{'blacklist'} = "script";
				$emaildata->{'blacklist_line'} = $lineNumber;
				$emaildata->{'blacklist_match'} = $_;
				return $emaildata;
			}
		}
	}
	#If we're here, script is either whitelisted or not-blacklisted.
	return $emaildata;
}

sub checkDirectoryBlacklist {
	# If the directory begins with anything on the blacklist
	# then the mail wont be sent. If it begins with 
	# anything on the whitelist then it will be sent. 
	my $c = shift;
	my $emaildata = shift;
	my $list;
	if(defined($c->{'directorywhitelist'})){
		$list = getList($c->{'directorywhitelist'});
		my $whitelisted = 0;
		foreach(keys(%$list)){
			if($emaildata->{'directory'} =~ m/^$_/){
			#directory is whitelisted
				return $emaildata;
			}
		}
		#if we're here, directory wasn't on the whitelist.
		return $emaildata;
	}elsif(defined($c->{'directoryblacklist'})){
		$list = getList($c->{'directoryblacklist'});
		foreach(keys(%$list)){
			if(my $lineNumber = $emaildata->{'directory'} =~ m/^$_/){
				$emaildata->{'blacklist'} = "directory";
				$emaildata->{'blackist_line'} = $lineNumber,
				$emaildata->{'blacklist_match'} = $emaildata->{'directory'};
				return $emaildata;
			}
		}
	}
	return $emaildata;
}


sub blacklist{
	my $emaildata = shift;
	my $errCode = shift;
	my $logLine = createLogLine($emaildata);
	my $fh_log;
	eval{
		open($fh_log, ">>", $c->{'blacklistlog'}) or die "Error opening blacklist log file '$c->{'blacklistlog'}";
	};
	if($@){
		_error($@);
	}else{
		print $fh_log $logLine;
	}
	printf($c->{'message'}, $errCode); ;
	exit 1;
}

sub getList{
	my $f_list = shift;
	my $fh_list;
	eval{
		open($fh_list, "<", $f_list) or die "Couldn't open list file $f_list : $!";
	};
	if($@){
		_error($@, "noexit");
		return;
	}
	my $list;
	my $lineNumber = 1;
	while(readline($fh_list)){
		chomp;
		next if $_ eq '';
		$list->{$_} = $lineNumber;
		$lineNumber++;
	}
	return $list;
}

sub sendmail{
	my $message = shift;
	my $args = shift;
	open( my $sendmail, "| $c->{'sendmail'}  @$args") 
	   or _error("error creating pipe to sendmail with \" | $c->{'sendmail'} ".join(" ", @$args)."\"\n");
	foreach(@$message){
		print $sendmail $_;
	}
	close $sendmail;
}

sub createLogLine{
	my $data = shift || $emaildata;
	my $l = getTime();
	if(defined($data->{'blacklist'})){
		$l.=" BLACKLIST($data->{'blacklist'}) ";
	}else{
		$l.=" SENT ";
	}
	$l.= "directory: $data->{'pwd'} ";
	$l.= "SCRIPT: $data->{'script'} ";
	$l.= "SCRIPTFILE: $data->{'scriptfilename'} ";
#	$l.= "CLIENT: $data->{'client'} ";
	$l.= "TO: $data->{'to'} ";
	$l.= "FROM: $data->{'from'} ";
#	$l.= "directory: $data->{'pwd'} ";
	$l.= "ARGS: $data->{'args_string'}";
	$l.= "\n";
	return $l
}

sub _log {
	my $logline = createLogLine();
	open(my $fh_log, ">>", $c->{'sentlog'}) or _error ("Unable to write to log file $c->{'sentlog'}\n", "noexit");
	print $fh_log $logline;
	close($fh_log);
}
sub _log_json {
	my $hash = shift;
	my $file = shift;
	return unless $file;
	open(my $fh_log, ">>", $file) or _error ("Unable to write to json log file $file\n", "noexit");
	$hash->{'time'} = time();
	print $fh_log encode_json($hash), "\n";
	close($fh_log);
}

sub _error {
	my $message = shift;
	my $exit = shift;
	my $old_umask = umask(000);
	my $logLine = $message." ".createLogLine();
	open( my $log, ">>", $c->{'errorlog'});
	print $log $logLine;
	exit 1 unless $exit =~ /noexit/i;
	umask $old_umask;
}

sub parseConfigFile{
	my $f_config = shift;
	open(my $fh_config, "<", $f_config) or _error("Couldn't open config file. Help! I have no idea what I'm doing!");
	my $config;
	while(readline($fh_config)){
		next unless (/^\s*(\S+)\s*=\s*(.+)#?\s*/);
		$config->{$1} = $2;
	}
	return $config;
}

sub getTime{
	my $epoch=time();
	my ($Y,$M,$D,$h,$m,$s)=(localtime($epoch))[5,4,3,2,1,0];
	return sprintf("%d %d-%02d-%02d %02d:%02d:%02d", $epoch, $Y+1900, $M+1, $D, $h, $m, $s);
}
