---
  package: sendmailwrapper
  maintainer: Avi Greenbury <ialoneambest@gmail.com>
  description: Logging/blacklisting sendmail wrapper for PHP
  requires:
    perl: 0
  dir_map: 
    scripts : /usr/local/scripts/bin
		var: /var
