--- 
description: "Logging/blacklisting sendmail wrapper for PHP"
dir_map: 
  scripts: /usr/local/scripts/bin
maintainer: "Avi Greenbury <ialoneambest@gmail.com>"
package: sendmailwrapper
requires: 
  perl: 0
